### PR TITLE
[feature] adding two new methods (get) and (count) to db_storage and …

### PR DESCRIPTION
**Pull request by HeimerR**
Adding two new methods (get) and (count) to db_storage and filestorage

### CODE REVIEW

**Review by yawzyag — COMMENTED** [review]
Add coments to your function pls

**Review by yawzyag — COMMENTED** [review]
Check pep8

**Comment by HeimerR** [comment]
pep8 was checked

**Review by yawzyag — APPROVED** [review]
All good 🥇

**Pull request merged**
